### ISSUE TITLE
Add unit tests for LoremImage component

### ISSUE THREAD

**Issue by CodeDraken** [CodeDraken/react-ipsum#1]
Use the LoremText component tests as an example.

**Comment by d-ivashchuk** [comment]
Hey @CodeDraken I will work on that!

**Comment by CodeDraken** [comment]
Great @d-ivashchuk be sure to check out the [storybook here](https://codedraken.github.io/react-ipsum/) to help understand how it works. I'll update the readme with setup instructions soon.
